const products = [
    {
      id: 7808456851650,
      gql_id: 'gid://shopify/ProductVariant/43975190577346',
      title: 'Automóvil Eléctrico de Núcleo Único',
      description: '<p>El futuro de la movilidad ha llegado con nuestro automóvil eléctrico de núcleo único. Rendimiento impresionante y cero emisiones.</p>',
      price: '36.18',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/7CNYas7.jpg?v=1706557009',
      quantity: 10,
      handle: 'automovil-electrico-de-nucleo-unico',
      handlec:'vehiculos',
      tags: 'Movilidad Eléctrica y Vehículos Autónomos'
    },
    {
      id: 7808456917186,
      gql_id: 'gid://shopify/ProductVariant/43975190741186',
      title: 'Coche Volador Eléctrico VTOL',
      description: '<p>Despega y aterriza en cualquier lugar con nuestro coche volador eléctrico VTOL. Convierte tus desplazamientos en una experiencia aérea.</p>',
      price: '37.77',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/jqppvYA.jpg?v=1706557012',
      quantity: 10,
      handle: 'coche-volador-electrico-vtol',
      handlec:'vehiculos',
      tags: 'Movilidad Eléctrica y Vehículos Autónomos'
    },
    {
      id: 7808457146562,
      gql_id: 'gid://shopify/ProductVariant/43975191068866',
      title: 'Compostador Autónomo',
      description: '<p>Reduce los residuos y convierte tus desechos orgánicos en abono con nuestro compostador autónomo. Fácil y ecológico.</p>',
      price: '47.36',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/ghnit4O.jpg?v=1706557025',
      quantity: 10,
      handle: 'compostador-autonomo',
      handlec: 'energia-renovable',
      tags: 'Energía Renovable y Sostenibilidad'
    },
    {
      id: 7808456392898,
      gql_id: 'gid://shopify/ProductVariant/43975187267778',
      title: 'Gafas de Realidad Virtual de Alta Resolución',
      description: '<p>Experimenta la realidad virtual como nunca antes con nuestras gafas de alta resolución. Sumérgete en mundos virtuales con detalles impresionantes y una claridad visual sorprendente.</p>',
      price: '25.00',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/pRPPiS4.jpg?v=1706556992',
      quantity: 10,
      handle: 'gafas-de-realidad-virtual-de-alta-resolucion',
      handlec: 'tecnologia-rv', 
      tags: 'Realidad aumentada y realidad virtual'
    },
    {
      id: 7808456425666,
      gql_id: 'gid://shopify/ProductVariant/43975187300546',
      title: 'Gafas para Detección de Riesgos Naturales',
      description: '<p>Mantente seguro en la naturaleza con nuestras gafas especializadas para la detección de riesgos naturales. Estas gafas te brindan información en tiempo real sobre peligros como incendios forestales, tormentas y terremotos.</p>',
      price: '19.99',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/O4AOc7s.jpg?v=1706556994',
      quantity: 10,
      handle: 'gafas-para-deteccion-de-riesgos-naturales',
      handlec: 'tecnologia-rv', 
      tags: 'Realidad aumentada y realidad virtual'
    },
    {
      id: 7808456491202,
      gql_id: 'gid://shopify/ProductVariant/43975187660994',
      title: 'Guantes de Realidad Virtual',
      description: '<p>Convierte tus manos en controladores precisos en el mundo virtual con nuestros guantes de realidad virtual. Siente y manipula objetos digitales con una precisión excepcional.</p>',
      price: '19.99',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/FfjoQ9g.jpg?v=1706556996',
      quantity: 10,
      handle: 'guantes-de-realidad-virtual',
      handlec: 'tecnologia-rv', 
      tags: 'Realidad aumentada y realidad virtual'
    },
    {
      id: 7808456556738,
      gql_id: 'gid://shopify/ProductVariant/43975187923138',
      title: 'Kit de Vuelo con Realidad Virtual',
      description: '<p>Domina los cielos con nuestro kit de vuelo de realidad virtual. Pilotea aviones y drones con precisión y realismo asombroso.</p>',
      price: '17.99',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/6NS4fG1.jpg?v=1706557000',
      quantity: 10,
      handle: 'kit-de-vuelo-con-realidad-virtual',
      handlec: 'tecnologia-rv', 
      tags: 'Realidad aumentada y realidad virtual'
    },
    {
      id: 7808456720578,
      gql_id: 'gid://shopify/ProductVariant/43975190151362',
      title: 'Kolibri: Asistente Volador Personal',
      description: '<p>El Kolibri es tu asistente volador personal. Este pequeño dron inteligente te sigue a donde vayas y te ayuda a capturar momentos impresionantes desde el aire.</p>',
      price: '32.98',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/gJgvlLX.jpg?v=1706557005',
      quantity: 10,
      handle: 'kolibri-asistente-volador-personal',
      handlec:'domotica-inteligente',
      tags: 'Domótica Inteligente'
    },
    {
      id: 7808456655042,
      gql_id: 'gid://shopify/ProductVariant/43975189823682',
      title: 'Luces Ambientales de Entorno Variable',
      description: '<p>Crea un ambiente único en tu hogar con nuestras luces ambientales. Cambia el entorno a tu gusto con una variedad de colores y efectos de iluminación.</p>',
      price: '31.38',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/5It5n7p.jpg?v=1706557003',
      quantity: 10,
      handle: 'luces-ambientales-de-entorno-variable',
      handlec:'domotica-inteligente',
      tags: 'Domótica Inteligente'
    },
    {
      id: 7808456982722,
      gql_id: 'gid://shopify/ProductVariant/43975190806722',
      title: 'Máscara Rejuvenecedora Instantánea',
      description: '<p>Rejuvenece tu piel al instante con nuestra máscara de belleza de última generación. Reduce arrugas y mejora la elasticidad de la piel en minutos.</p>',
      price: '40.97',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/TEcvsje.jpg?v=1706557016',
      quantity: 10,
      handle: 'mascara-rejuvenecedora-instantanea',
      handlec: 'salud-y-bienestar-tecnologico',
      tags: 'Salud y Bienestar Tecnológico'
    },
    {
      id: 7808456949954,
      gql_id: 'gid://shopify/ProductVariant/43975190773954',
      title: 'Monociclo Eléctrico de Autoequilibrio',
      description: '<p>Navega por la ciudad con estilo en nuestro monociclo eléctrico de autoequilibrio. Movimiento suave y control intuitivo.</p>',
      price: '39.37',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/cncoWWV.jpg?v=1706557014',
      quantity: 10,
      handle: 'monociclo-electrico-de-autoequilibrio',
      handlec:'vehiculos',
      tags: 'Movilidad Eléctrica y Vehículos Autónomos'
    },
    {
      id: 7808457113794,
      gql_id: 'gid://shopify/ProductVariant/43975191036098',
      title: 'Paneles Solares Cristalinos',
      description: '<p>Genera energía limpia y sostenible con nuestros paneles solares cristalinos. Perfectos para tu hogar o negocio.</p>',
      price: '45.76',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/ChntT0T.jpg?v=1706557023',
      quantity: 10,
      handle: 'paneles-solares-cristalinos',
      handlec: 'energia-renovable',
      tags: 'Energía Renovable y Sostenibilidad'
    },
    {
      id: 7808457212098,
      gql_id: 'gid://shopify/ProductVariant/43975191134402',
      title: 'Pulsera Eternal Health',
      description: '<p>Tu salud y bienestar son lo primero con nuestra pulsera Eternal Health. Controla tus signos vitales y recibe recomendaciones personalizadas.</p>',
      price: '50.56',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/vtxI77V.jpg?v=1706557029',
      quantity: 10,
      handle: 'pulsera-eternal-health',
      handlec: 'ropa-y-wereables',
      tags: 'Vestimenta Inteligente y Wearables de Moda'
    },
    {
      id: 7808457015490,
      gql_id: 'gid://shopify/ProductVariant/43975190839490',
      title: 'Regenerador Muscular',
      description: '<p>Alivia la fatiga muscular y acelera la recuperación con nuestro regenerador muscular. Ideal para atletas y personas activas.</p>',
      price: '42.57',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/6ivp3De.jpg?v=1706557018',
      quantity: 10,
      handle: 'regenerador-muscular',
      handlec: 'salud-y-bienestar-tecnologico',
      tags: 'Salud y Bienestar Tecnológico'
    },
    {
      id: 7808456753346,
      gql_id: 'gid://shopify/ProductVariant/43975190479042',
      title: 'Robot Aspirador Autónomo',
      description: '<p>Mantén tu hogar impecable sin esfuerzo con nuestro robot aspirador autónomo. Se mueve de forma inteligente, aspirando el polvo y la suciedad en cada rincón.</p>',
      price: '34.58',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/LAiD8V9.jpg?v=1706557007',
      quantity: 10,
      handle: 'robot-aspirador-autonomo',
      handlec:'domotica-inteligente',
      tags: 'Domótica Inteligente'
    },
    {
      id: 7808457179330,
      gql_id: 'gid://shopify/ProductVariant/43975191101634',
      title: 'Smart Socks',
      description: "<p>Mantén un seguimiento detallado de tu rendimiento físico con nuestros 'smart socks' que registran datos sobre tu pisada y movimiento.</p>",
      price: '48.96',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/ABFSNeo.jpg?v=1706557027',
      quantity: 10,
      handle: 'smart-socks',
      handlec: 'ropa-y-wereables',
      tags: 'Vestimenta Inteligente y Wearables de Moda'
    },
    {
      id: 7808457310402,
      gql_id: 'gid://shopify/ProductVariant/43975191265474',
      title: 'Traje de Buzo de Alta Profundidad',
      description: '<p>Explora las profundidades del océano con nuestro traje de buzo de alta profundidad. Diseñado para aventureros submarinos y exploradores.</p>',
      price: '53.75',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/rldXbjA.jpg?v=1706557033',
      quantity: 10,
      handle: 'traje-de-buzo-de-alta-profundidad',
       handlec: 'ropa-y-wereables',
      tags: 'Vestimenta Inteligente y Wearables de Moda'
    },
    {
      id: 7808456523970,
      gql_id: 'gid://shopify/ProductVariant/43975187890370',
      title: 'Traje Hayabusa Gamer para Realidad Virtual',
      description: '<p>Experimenta la verdadera inmersión en juegos con el traje Hayabusa para realidad virtual. Este traje proporciona retroalimentación táctil y una experiencia de juego de otro nivel.</p>',
      price: '49.99',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/gi7oY89.jpg?v=1706556998',
      quantity: 10,
      handle: 'traje-hayabusa-gamer-para-realidad-virtual',
      handlec: 'tecnologia-rv', 
      tags: 'Realidad aumentada y realidad virtual'
    },
    {
      id: 7808457048258,
      gql_id: 'gid://shopify/ProductVariant/43975190872258',
      title: 'Transformador Morfológico Facial',
      description: '<p>Experimenta la transformación de tu rostro con nuestro transformador morfológico facial. Maquillaje y efectos especiales de otro nivel.</p>',
      price: '44.17',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/utW8iEw.jpg?v=1706557021',
      quantity: 10,
      handle: 'transformador-morfologico-facial',
      handlec: 'salud-y-bienestar-tecnologico',
      tags: 'Salud y Bienestar Tecnológico'
    },
    {
      id: 7808457277634,
      gql_id: 'gid://shopify/ProductVariant/43975191232706',
      title: 'Zapatillas Deportivas Inteligentes',
      description: '<p>Supera tus límites en el deporte con nuestras zapatillas deportivas inteligentes que registran métricas de rendimiento y brindan retroalimentación en tiempo real.</p>',
      price: '52.16',
      image: 'https://cdn.shopify.com/s/files/1/0639/8620/4866/products/WyOuIma.jpg?v=1706557031',
      quantity: 10,
      handle: 'zapatillas-deportivas-inteligentes',
       handlec: 'ropa-y-wereables',
      tags: 'Vestimenta Inteligente y Wearables de Moda'
    }
  ]
export async function GET() {
    return Response.json({products })
}