export const env = {
    SHOPYFY_APY_KEY: process.env.SHOPYFY_APY_KEY|| "",
    SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME || "",
    CACHE_TOKEN:process.env.CACHE_TOKEN,
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_ID:process.env.FIREBASE_ID
}
