export const env = {
    SHOPYFY_APY_KEY: process.env.SHOPYFY_APY_KEY|| "",
    SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME || "",
    CACHE_TOKEN:process.env.CACHE_TOKEN,
    FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_ID:process.env.NEXT_PUBLIC_FIREBASE_ID
}
